name: exercise_finder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  injectable: ^2.3.2
  provider: ^6.1.1
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  internet_connection_checker_plus: ^2.2.0
  envied: ^0.5.3
  pretty_dio_logger: ^1.3.1
  skeletonizer: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_slidable: ^3.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  envied_generator: ^0.5.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
